### ISSUE TITLE
Webcoket?

### ISSUE THREAD

**Issue by mzch** [usatiuk/writer#25]
I found `WebSocket error` as below:

```
hmr-runtime.js:29 WebSocket connection to 'wss://notewriter.org:32999/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Could anyone tell me how to fix this issue?

**Comment by usatiuk** [comment]
Hi! And thank you for interest in this thing 😁

I'm pretty sure that this happens because you're not using the production build of the frontend.
You should build it with `npm run build` (in `frontend` directory) and the backend will serve the static files if you just run it with `npm start`

An easier alternative would be using a docker container, which you can read about in the updated documentation

**Comment by mzch** [comment]
Mm...I ran `npm run build` and frontend static file is served by Apache.
Another Chrome console message:
```
WebSocket connection to 'wss://notewriter.org:45035/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
It seems to randomize port...

**Comment by usatiuk** [comment]
Hm, it's weird
I looked at notewriter.org, and it seems that the frontend (according to React firefox extension) is, indeed, using production build of React. But for whatever reason `src.ee49605d.js` still has HMR builtin. 🤔

One thing to keep in mind is that `parcel serve/watch` actually overwrites files created by `parcel build`, so if you had run this command after building the frontend, it would have replaced the production build with dev build. (although in my case React extension also shows this)

Could you run `npm run build` again, and not run `npm run dev` or anything similar afterwards?

**Comment by mzch** [comment]
Well, `API_ROOT` seems to be ignored. I put separated config into Apache, e.g. `API_ROOT=https://api.notewriter.org`, `WEB_ROOT=https://notewriter.org`

Then I put the following config and got successful responses. Thank!

```apache
<IfModule mod_ssl.c>
<VirtualHost *:443>

	ServerName notewriter.org
	ServerAlias www.notewriter.org
	ServerAdmin webmaster@notewriter.org

	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateFile /etc/letsencrypt/live/notewriter.org/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/notewriter.org/privkey.pem

	RewriteEngine On
	RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
	RewriteRule ^(.*)$ https://%1/$1 [R=301,L]

	RequestHeader set X-Forwarded-Proto "https"
	ProxyPreserveHost On
	ProxyRequests Off

	ProxyPass / http://127.0.0.1:3000/
	ProxyPassReverse / http://127.0.0.1:3000/

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
</IfModule>
```
